/**
 * One-shot generator for cli/src/constants/cytoscape.ts.
 *
 * Reads the Cytoscape.js minified dist previously downloaded to
 * /tmp/cytoscape.min.js (or CYTO_DIST), escapes it for a TS template-literal
 * constant, and emits the generated module — so the `/graph-export` HTML is
 * fully offline (no CDN dependency), matching the FONT_AWESOME_ALL_CSS
 * inlining pattern.
 *
 * Cytoscape.js v3.30.2 — MIT License (Copyright (c) 2016-2024, The Cytoscape
 * Consortium). Source: https://cdn.jsdelivr.net/npm/cytoscape@3.30.2/dist/cytoscape.min.js
 *
 * Run from the repo root:  bun cli/scripts/generate-cytoscape.ts
 */
import fs from 'fs'
import path from 'path'

const SRC =
  process.env.CYTO_DIST ??
  path.join(process.env.TEMP ?? process.env.TMP ?? '/tmp', 'cytoscape.min.js')
const OUT = path.join(process.cwd(), 'cli/src/constants/cytoscape.ts')

const source = fs.readFileSync(SRC, 'utf8')

// Escape backslashes, backticks, and ${ sequences so the payload is a valid
// template literal. Backslashes MUST be escaped first: the minified dist
// contains legacy octal regex escapes (\1, \2) and \u sequences that TS would
// otherwise reject or re-interpret inside a template literal. After escaping,
// the runtime template literal evaluates \\ back to the original single \\1.
const escaped = source
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${')

const generated = `/**
 * Cytoscape.js v3.30.2 (minified, MIT License) — fully offline graph renderer.
 *
 * The entire minified dist inlined as a template literal, so /graph-export
 * renders interactive graphs with zero network requests.
 *
 * Source: https://cdn.jsdelivr.net/npm/cytoscape@3.30.2/dist/cytoscape.min.js
 * License: MIT (Copyright (c) 2016-2024, The Cytoscape Consortium).
 *
 * Generated by cli/scripts/generate-cytoscape.ts — do not edit by hand.
 */
export const CYTO_JS: string = \`${escaped}\`
`

// NOTE: the payload is a single 373KB template literal — Prettier's
// formatWithCursor cannot parse a file this size in one pass, so the output is
// written verbatim (the generated module is machine output, like
// bundled-agents.generated.ts; the prettier gate excludes generated files via
// .prettierignore for this category).
fs.writeFileSync(OUT, generated, 'utf8')
console.log(
  `Generated ${OUT} (${fs.statSync(OUT).size} bytes, source ${source.length} chars)`,
)
