/**
 * One-shot generator for cli/src/constants/fontawesome.ts.
 *
 * Reads the Font Awesome Free 6.7.2 assets previously downloaded to
 * %LOCALAPPDATA%/Temp/fa-offline (Git Bash `/tmp` maps there on Windows),
 * rewrites every `url(../webfonts/*.woff2)` reference to a base64 data URI,
 * strips the `.ttf` fallbacks (woff2 is universally supported; a relative ttf
 * URL would 404 offline), and emits a TS template-literal constant with all
 * backslashes escaped.
 *
 * The base64 payloads are emitted un-wrapped so literal newlines never appear
 * inside a CSS url() token (a parse error per the CSS spec and fragile across
 * browsers).
 *
 * Run from the repo root:  bun cli/scripts/generate-fontawesome.ts
 */
import fs from 'fs'
import path from 'path'

const FA_DIR =
  process.env.FA_OFFLINE_DIR ??
  path.join(process.env.LOCALAPPDATA ?? '.', 'Temp', 'fa-offline')
const OUT = path.join(process.cwd(), 'cli/src/constants/fontawesome.ts')

const css = fs.readFileSync(path.join(FA_DIR, 'all.min.css'), 'utf8')

const FONT_NAMES = [
  'fa-brands-400',
  'fa-regular-400',
  'fa-solid-900',
  'fa-v4compatibility',
]

const fonts: Record<string, string> = {}
for (const name of FONT_NAMES) {
  fonts[name] = fs
    .readFileSync(path.join(FA_DIR, `${name}.woff2`))
    .toString('base64')
}

// 1. Drop ttf fallbacks: `,url(../webfonts/fa-solid-900.ttf) format("truetype")`
let out = css.replace(
  /,url\(\.\.\/webfonts\/[a-z0-9-]+\.ttf\) format\("truetype"\)/g,
  '',
)

// 2. Replace every woff2 ref with a base64 data URI
out = out.replace(
  /url\(\.\.\/webfonts\/([a-z0-9-]+)\.woff2\)/g,
  (_m, name: string) => {
    const b64 = fonts[name]
    if (!b64) throw new Error(`Missing font: ${name}`)
    return `url(data:font/woff2;base64,${b64})`
  },
)

// 3. Escape for embedding in a TS template literal: backslash, backtick, ${.
out = out
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${')

const header = `/**
 * Font Awesome Free 6.7.2 (webfonts) — fully offline stylesheet.
 *
 * The entire \`all.min.css\` with every webfont (brands/regular/solid/v4-compat)
 * embedded as base64 data URIs, so the exported HTML report renders all icons
 * identically with zero network requests.
 *
 * Source: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.7.2/
 * License: Icons CC BY 4.0, Fonts SIL OFL 1.1, Code MIT License.
 *
 * Generated by cli/scripts/generate-fontawesome.ts — do not edit by hand.
 */
export const FONT_AWESOME_ALL_CSS: string =
  \`${out}\`
`

fs.writeFileSync(OUT, header)
const kb = (Buffer.byteLength(header, 'utf8') / 1024).toFixed(1)
console.log(`Wrote ${OUT} (${kb} KB)`)
