import fs from 'fs'
import path from 'path'

const entry = path.join(process.cwd(), 'cli/scripts/sigma-entry.ts')
const output = path.join(process.cwd(), 'cli/src/constants/sigma.ts')
const result = await Bun.build({
  entrypoints: [entry],
  outdir: '/tmp/savant-sigma-bundle',
  target: 'browser',
  minify: true,
  format: 'iife',
  naming: 'sigma-runtime.js',
})
if (!result.success) {
  throw new Error(result.logs.map((log) => log.message).join('\n'))
}
const bundlePath = '/tmp/savant-sigma-bundle/sigma-runtime.js'
const source = fs.readFileSync(bundlePath, 'utf8')
const escaped = source
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${')
const generated = `/**
 * Sigma.js + Graphology browser runtime for the offline Code Universe export.
 * Generated by cli/scripts/generate-sigma.ts; do not edit manually.
 */
export const SIGMA_JS: string = \`${escaped}\`
`
fs.writeFileSync(output, generated, 'utf8')
const written = fs.readFileSync(output, 'utf8')
if (written !== generated) {
  throw new Error(
    'Generated Sigma runtime failed the write/read reproducibility check',
  )
}
console.log(`Generated ${output} (${Buffer.byteLength(generated)} bytes)`)
